version: "3.1"

services:
    mariadb:
      image: mariadb:10.1
      container_name: mariadb
      working_dir: /var/www/web
      volumes:
      - .docker/mysql/db.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=ocodesig_homestead
        - MYSQL_USER=ocodesig_db
        - MYSQL_PASSWORD=admin_db2018
      ports:
        - "8891:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /var/www/web
      volumes:
          - .:/var/www/web
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: php
      working_dir: /var/www/web
      volumes:
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - .:/var/www/web

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mariadb:mariadb
      ports:
        - 9191:80
      environment:
        MYSQL_USERNAME: ocodesig_db
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_PASSWORD: admin_db2018
        PMA_HOST: mariadb
